from enum import Enum, auto


class ModelType(Enum):
    lenet5 = auto()
    resnet18_bn = auto()
    resnet18_gn = auto()
    resnet34 = auto()
    resnet50 = auto()
    simplenet = auto()
    cct_7_3x1_32 = auto()
    cct_7_7x2_224 = auto()
    cct_14_7x2_224 = auto()
    vit_b_16 = auto()
    vit_b_32 = auto()
    lenet5_large_fc = auto()
    mobilenet_v3_small = auto()
    mobilenet_v3_large = auto()
    mobilenet_v2 = auto()
    lenet4 = auto()
    vgg11_no_bn = auto()
    vgg11_bn = auto()
    efficientnet_b0 = auto()
    efficientnet_b1 = auto()
    efficientnet_v2_s = auto()
    shufflenet_v2 = auto()
    shufflenet_v2_x2_0 = auto()
    squeezenet1_1 = auto()
    mnasnet0_5 = auto()
    mnasnet1_0 = auto()
    densenet121 = auto()
    densenet_cifar = auto()
    regnet_x_200mf = auto()
    regnet_y_400mf = auto()
    convnext_tiny = auto()
    alexnet = auto()
    resnext50_32x4d = auto()
    wide_resnet50_2 = auto()
    dla = auto()
    dla_46_c = auto()

    ddpm_cifar10 = auto()
    nanoclip_default = auto()
    transformer_for_grokking = auto()